### ISSUE TITLE
Cannot perform private transaction using eeajs library

### ISSUE THREAD

**Issue by ab-chowdhury** [PegaSysEng/eeajs#21]
In eeajs library which supports private transactions,

I have updated the keys.js file to include:

1) Orion node public keys
2) Pantheon node RPC URLs
3) Pantheon node private keys

&

chainID specified in the genesis file for my network is not 2018 , and I have updated it in deployContract.js, storeValueFromNode1.js, and storeValueFromNode2.js

now from example/multiNodeExample directory when I am trying to deploy the contract using :

node deployContract.js

I am getting the following error

TypeError: Cannot read property 'data' of undefined
at web3.eea.getTransactionCount.then.then.catch.error (/home/dev/Music/pantheon-orion/eeajs/src/index.js:177:47)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)
![Screenshot from 2019-06-06 17-09-08](https://user-images.githubusercontent.com/45105422/59030245-1751bb80-887e-11e9-805f-9fc6da2c3abd.png)

I have performed steps as given in the following link:

https://docs.pantheon.pegasys.tech/en/latest/Privacy/Creating-Sending-Private-Transactions/#using-multinode-example

But I got stuck in 5th step.

**Comment by ekellstrand** [comment]
Identified logging issue https://pegasys1.atlassian.net/browse/PAN-2764 and provided temporary workaround to get at the real issue here.  ab-chowdhury confirmed things are working on gitter.
